# Generated by Django 2.2.8 on 2021-11-25 18:31

from django.db import migrations, models
import django.db.models.deletion
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destinataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('domaine_expertise', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_etude', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('cv', models.FileField(storage=djongo.storage.GridFSStorage(base_url='http://127.0.0.1:8000/cvs/', collection='cvs'), upload_to='cvs')),
                ('rapport_stage', models.FileField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='http://127.0.0.1:8000/rapports/', collection='rapports'), upload_to='rapports')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compte', to='eptGSI.Compte')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100)),
                ('descriptif_projet', models.TextField()),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Planning', to='eptGSI.Planning')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Programme', to='eptGSI.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Projet', to='eptGSI.Projet')),
            ],
        ),
        migrations.CreateModel(
            name='SousTache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=100)),
                ('echeance', models.DateField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('descriptif', models.TextField()),
                ('commentaire', models.TextField()),
                ('etat', models.BooleanField(default=False)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tache', to='eptGSI.Tache')),
            ],
        ),
        migrations.CreateModel(
            name='RespEntreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RespEntreprise', to='eptGSI.Membre')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Message', to='eptGSI.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='MembreDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MembreDept', to='eptGSI.Membre')),
            ],
        ),
        migrations.CreateModel(
            name='MaitreStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaitreStage', to='eptGSI.Membre')),
                ('planning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MaitreStage', to='eptGSI.Planning')),
            ],
        ),
        migrations.CreateModel(
            name='Immersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('annee', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Immersion', to='eptGSI.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('intitule', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('destinataire', models.ManyToManyField(to='eptGSI.Destinataire')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_evaluation', models.FloatField()),
                ('appreciation', models.TextField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Evaluation', to='eptGSI.Etudiant')),
                ('maitre_de_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Evaluation', to='eptGSI.MaitreStage')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='immersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Immersion', to='eptGSI.Immersion'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Membre', to='eptGSI.Membre'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='eptGSI.Planning'),
        ),
        migrations.CreateModel(
            name='ChefDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChefDept', to='eptGSI.Membre')),
            ],
        ),
    ]
