# Generated by Django 2.2.8 on 2021-11-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eptGSI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='compte',
        ),
        migrations.AddField(
            model_name='membre',
            name='compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compte', to='eptGSI.Compte'),
        ),
    ]
