# Generated by Django 2.2.8 on 2021-12-04 15:41

from django.db import migrations, models
import django.db.models.deletion
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('eptGSI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(storage=djongo.storage.GridFSStorage(base_url='http://127.0.0.1:8000/pjs/', collection='pjs'), upload_to='pjs')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PieceJointe', to='eptGSI.Evenement')),
            ],
        ),
    ]
