# Generated by Django 2.2.8 on 2021-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eptGSI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='identifiant',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
